"""remove coffee turns

Revision ID: 2c0f2f2e3784
Revises: 
Create Date: 2026-03-29 15:48:48.207519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c0f2f2e3784'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_session', schema=None) as batch_op:
        batch_op.drop_column('coffee_zero_turns')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coffee_zero_turns', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
